author: Lavy01
name: CoordList
main: com.lavy01.coordlist.CoordList
api: spigot
version: 0.0.1
api-version: 1.20.1
description: Easy store for your favorite coordinates!
commands:
  coordlist:
    usage: /<command> [help | add | remove | list | loop]
