author: Lavy01
name: CoordList
main: com.lavy01.coordlist.CoordList
api: spigot
version: 0.1.0
api-version: 1.20
description: A Minecraft Spigot plugin to manage your world coords.
commands:
  coordlist:
    description: Access to all CoordList features using just this command.
    usage: /<command> [help | add | remove | rename | clear | view | track]
    aliases: [cl]
